name = "High Fabric"
author = "Teleheel"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5d5cfc70111ce27b284f259c0af18b8bc1307ca1af92a68607d86854df6884dc"

[versions]
fabric = "0.14.21"
minecraft = "1.20.1"
