name = "High Fabric"
author = "Teleheel"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cbae6c412472bb3bb39c6e09f55c94423c564730f169f9c48603bccab0414496"

[versions]
fabric = "0.14.21"
minecraft = "1.20.1"
