name = "High Fabric"
author = "Teleheel"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "10d8d72a3991da382ee21da33c86601a7ceb0a17559af085ed3bc0fa1fa93b75"

[versions]
fabric = "0.14.21"
minecraft = "1.20.1"
