name = "High Fabric"
author = "Teleheel"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b992e6b600f89f10fa60d9cd59744938224a199153ca051ecfc9df698cd44f60"

[versions]
fabric = "0.14.21"
minecraft = "1.20.1"
