name = "High Fabric"
author = "Teleheel"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9726546bfa1a7eefc566164a603e5fbd4b0b7fabb18fdb03785b01b5464b3caf"

[versions]
fabric = "0.14.21"
minecraft = "1.20.1"
