name = "High Fabric"
author = "Teleheel"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0363bbf52b3a317c0c0cef61750560c30b61126535833d279bd7e4054eebf1f5"

[versions]
fabric = "0.14.21"
minecraft = "1.20.1"
