name = "High Fabric"
author = "Teleheel"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "254f3efc93c676d6084f23bddb776d5b2c0e565e16adde284ac9e75eda7ef981"

[versions]
fabric = "0.14.21"
minecraft = "1.20.1"
